/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 railingFence.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/railingFence.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Fence_01_Canal_LOD0_Fence_01_Main_0002.geometry} material={materials.Fence_01_Main} />
    </group>
  )
}

useGLTF.preload('/railingFence.glb')
