/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 fence.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/fence.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Fence_lp001.geometry} material={materials['Fence_mat.001']} position={[1.045, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/fence.glb')
