/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 railingGate.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function RailingGate(props) {
  const { nodes, materials } = useGLTF('/railingGate.glb')
  return (
    <group {...props} dispose={null} rotation={[0, 0, -Math.PI/2]} castShadow>
      <mesh geometry={nodes.Fence_01_Gate_LOD0001_Fence_01_Gate_0.geometry} material={materials.Fence_01_Gate} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.958, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/railingGate.glb')
